steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME"
      - "."
    id: "docker-build"
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME"
